hqapi.base.url=https://pannes.hydroquebec.com/pannes/donnees/v3_0/
hqapi.version.suffix=bisversion.json
hqapi.query.prefix=bismarkers
hqapi.query.suffix=.json
statistics.folder=HQstats
logs.folder=logs
postexporter.endpoint=
daemon.refresh.seconds=60
